export interface ItemPlanoLeitura {
  dia: number;
  referencia: string;
  titulo: string;
}

export interface PlanoLeitura {
  id: string;
  titulo: string;
  subtitulo: string;
  dias: ItemPlanoLeitura[];
}

export const PLANOS_LEITURA: PlanoLeitura[] = [
  {
    id: 'plano_fundamentos_fe_2026_v1',
    titulo: 'Fundamentos da Fé',
    subtitulo: 'Uma jornada rápida de 3 dias pelas origens da criação e a queda.',
    dias: [
      { dia: 1, referencia: 'Gênesis 1', titulo: 'A criação do mundo e do homem' },
      { dia: 2, referencia: 'Gênesis 2', titulo: 'O Jardim do Éden e o propósito' },
      { dia: 3, referencia: 'Gênesis 3', titulo: 'A desobediência e a promessa' },
    ],
  },
  {
    id: 'plano_coracao_pastor_2026_v1',
    titulo: 'O Coração do Pastor',
    subtitulo: '5 dias de refrigério espiritual através dos Salmos mais marcantes.',
    dias: [
      { dia: 1, referencia: 'Salmos 1', titulo: 'O caminho do bem e do mal' },
      { dia: 2, referencia: 'Salmos 8', titulo: 'A majestade de Deus e a dignidade humana' },
      { dia: 3, referencia: 'Salmos 23', titulo: 'O Senhor é o meu pastor' },
      { dia: 4, referencia: 'Salmos 27', titulo: 'O Senhor é a minha luz e salvação' },
      { dia: 5, referencia: 'Salmos 91', titulo: 'A habitação no esconderijo do Altíssimo' },
    ],
  },
  {
    id: 'plano_sabedoria_pratica_2026_v1',
    titulo: 'Sabedoria Diária',
    subtitulo: '7 dias de conselhos práticos para a vida em Provérbios.',
    dias: [
      { dia: 1, referencia: 'Provérbios 1', titulo: 'O princípio da sabedoria' },
      { dia: 2, referencia: 'Provérbios 3', titulo: 'Confiança e direção em Deus' },
      { dia: 3, referencia: 'Provérbios 4', titulo: 'As duas veredas da vida' },
      { dia: 4, referencia: 'Provérbios 15', titulo: 'Palavras que edificam' },
      { dia: 5, referencia: 'Provérbios 16', titulo: 'Os planos do coração' },
      { dia: 6, referencia: 'Provérbios 22', titulo: 'A boa reputação e a prudência' },
      { dia: 7, referencia: 'Provérbios 31', titulo: 'O valor da virtude' },
    ],
  },
  {
    id: 'plano_passos_mestre_2026_v1',
    titulo: 'Caminhando com o Mestre',
    subtitulo: '10 dias conhecendo os passos, milagres e ensinamentos de Jesus em Marcos.',
    dias: [
      { dia: 1, referencia: 'Marcos 1', titulo: 'O início do ministério e batismo' },
      { dia: 2, referencia: 'Marcos 2', titulo: 'O poder para perdoar pecados' },
      { dia: 3, referencia: 'Marcos 4', titulo: 'Parábolas do Reino e tempestade' },
      { dia: 4, referencia: 'Marcos 5', titulo: 'Transformação de vidas e cura' },
      { dia: 5, referencia: 'Marcos 8', titulo: 'A identidade de Cristo e o discípulo' },
      { dia: 6, referencia: 'Marcos 9', titulo: 'A transfiguração e a fé' },
      { dia: 7, referencia: 'Marcos 10', titulo: 'O jovem rico e o verdadeiro servo' },
      { dia: 8, referencia: 'Marcos 12', titulo: 'O maior mandamento' },
      { dia: 9, referencia: 'Marcos 14', titulo: 'A última ceia e o Getsêmani' },
      { dia: 10, referencia: 'Marcos 16', titulo: 'A ressurreição e a Grande Comissão' },
    ],
  },
  {
    id: 'plano_vida_espirito_2026_v1',
    titulo: 'A Vida no Espírito',
    subtitulo: '14 dias profundos de transformação e justificação na carta aos Romanos.',
    dias: [
      { dia: 1, referencia: 'Romanos 1', titulo: 'O poder do evangelho' },
      { dia: 2, referencia: 'Romanos 2', titulo: 'O justo juízo de Deus' },
      { dia: 3, referencia: 'Romanos 3', titulo: 'A justificação pela fé' },
      { dia: 4, referencia: 'Romanos 4', titulo: 'O exemplo de Abraão' },
      { dia: 5, referencia: 'Romanos 5', titulo: 'Paz com Deus e a graça' },
      { dia: 6, referencia: 'Romanos 6', titulo: 'Mortos para o pecado, vivos para Deus' },
      { dia: 7, referencia: 'Romanos 7', titulo: 'O conflito interior' },
      { dia: 8, referencia: 'Romanos 8', titulo: 'A vida no Espírito' },
      { dia: 9, referencia: 'Romanos 10', titulo: 'A confissão de fé e a salvação' },
      { dia: 10, referencia: 'Romanos 12', titulo: 'O culto racional e a transformação' },
      { dia: 11, referencia: 'Romanos 13', titulo: 'O amor ao próximo e a conduta' },
      { dia: 12, referencia: 'Romanos 14', titulo: 'A acolhida na diversidade da fé' },
      { dia: 13, referencia: 'Romanos 15', titulo: 'A esperança para os gentios' },
      { dia: 14, referencia: 'Romanos 16', titulo: 'Saudações finais e doxologia' },
    ],
  },
  {
    id: 'plano_vida_cristo_30d_2026_v1',
    titulo: 'A Vida de Cristo (Os 4 Evangelhos)',
    subtitulo: 'Os 30 eventos mais marcantes de Jesus na terra, do nascimento à ressurreição.',
    dias: [
      { dia: 1, referencia: 'Lucas 1', titulo: 'O anúncio do nascimento' },
      { dia: 2, referencia: 'Lucas 2', titulo: 'O nascimento de Jesus' },
      { dia: 3, referencia: 'Mateus 3', titulo: 'O batismo de Jesus' },
      { dia: 4, referencia: 'Mateus 4', titulo: 'A tentação no deserto' },
      { dia: 5, referencia: 'João 2', titulo: 'O primeiro milagre em Caná' },
      { dia: 6, referencia: 'João 3', titulo: 'O encontro com Nicodemos' },
      { dia: 7, referencia: 'João 4', titulo: 'A mulher samaritana' },
      { dia: 8, referencia: 'Lucas 5', titulo: 'A pesca maravilhosa e os primeiros discípulos' },
      { dia: 9, referencia: 'Mateus 5', titulo: 'O Sermão do Monte (As Bem-Aventuranças)' },
      { dia: 10, referencia: 'Mateus 6', titulo: 'O Sermão do Monte (Oração e Ansiedade)' },
      { dia: 11, referencia: 'Mateus 7', titulo: 'O Sermão do Monte (Dois Caminhos)' },
      { dia: 12, referencia: 'Marcos 4', titulo: 'Acalmando a tempestade' },
      { dia: 13, referencia: 'Marcos 5', titulo: 'A cura da mulher do fluxo de sangue' },
      { dia: 14, referencia: 'João 6', titulo: 'A multiplicação dos pães' },
      { dia: 15, referencia: 'Mateus 14', titulo: 'Andando sobre as águas' },
      { dia: 16, referencia: 'Mateus 16', titulo: 'A confissão de Pedro' },
      { dia: 17, referencia: 'Marcos 9', titulo: 'A Transfiguração' },
      { dia: 18, referencia: 'Lucas 10', titulo: 'A parábola do Bom Samaritano' },
      { dia: 19, referencia: 'Lucas 15', titulo: 'Ovelha Perdida e o Filho Pródigo' },
      { dia: 20, referencia: 'João 11', titulo: 'A ressurreição de Lázaro' },
      { dia: 21, referencia: 'Lucas 19', titulo: 'Zaqueu e a Entrada Triunfal' },
      { dia: 22, referencia: 'João 13', titulo: 'O lava-pés e a humildade' },
      { dia: 23, referencia: 'João 14', titulo: 'A promessa do Espírito Santo' },
      { dia: 24, referencia: 'João 15', titulo: 'A videira verdadeira' },
      { dia: 25, referencia: 'João 17', titulo: 'A oração sacerdotal de Jesus' },
      { dia: 26, referencia: 'Mateus 26', titulo: 'O Getsêmani e a Prisão' },
      { dia: 27, referencia: 'Mateus 27', titulo: 'A Crucificação' },
      { dia: 28, referencia: 'Lucas 24', titulo: 'A Ressurreição e o caminho de Emaús' },
      { dia: 29, referencia: 'João 20', titulo: 'Jesus aparece aos discípulos' },
      { dia: 30, referencia: 'Mateus 28', titulo: 'A Grande Comissão' },
    ],
  },
  {
    id: 'plano_salmos_30d_2026_v1',
    titulo: '30 Dias de Adoração nos Salmos',
    subtitulo: 'Um mês mergulhando nos cânticos e orações mais profundos da Bíblia.',
    dias: [
      { dia: 1, referencia: 'Salmos 1', titulo: 'A felicidade dos justos' },
      { dia: 2, referencia: 'Salmos 8', titulo: 'A majestade divina' },
      { dia: 3, referencia: 'Salmos 15', titulo: 'Quem habitará no teu santuário?' },
      { dia: 4, referencia: 'Salmos 19', titulo: 'A glória de Deus na criação e na lei' },
      { dia: 5, referencia: 'Salmos 23', titulo: 'O Supremo Pastor' },
      { dia: 6, referencia: 'Salmos 24', titulo: 'O Rei da Glória' },
      { dia: 7, referencia: 'Salmos 27', titulo: 'Confiança total em Deus' },
      { dia: 8, referencia: 'Salmos 32', titulo: 'A alegria do perdão' },
      { dia: 9, referencia: 'Salmos 34', titulo: 'O Senhor livra os aflitos' },
      { dia: 10, referencia: 'Salmos 37', titulo: 'Não te indignes por causa dos malfeitores' },
      { dia: 11, referencia: 'Salmos 40', titulo: 'Esperei com paciência no Senhor' },
      { dia: 12, referencia: 'Salmos 42', titulo: 'A sede da alma por Deus' },
      { dia: 13, referencia: 'Salmos 46', titulo: 'Deus é o nosso refúgio e fortaleza' },
      { dia: 14, referencia: 'Salmos 51', titulo: 'Oração de arrependimento (Davi)' },
      { dia: 15, referencia: 'Salmos 63', titulo: 'O anseio por Deus no deserto' },
      { dia: 16, referencia: 'Salmos 73', titulo: 'O fim dos ímpios e a paz dos justos' },
      { dia: 17, referencia: 'Salmos 84', titulo: 'Quão amáveis são os teus tabernáculos' },
      { dia: 18, referencia: 'Salmos 90', titulo: 'A eternidade de Deus e a fragilidade humana' },
      { dia: 19, referencia: 'Salmos 91', titulo: 'A segurança daquele que confia' },
      { dia: 20, referencia: 'Salmos 95', titulo: 'Convite para adoração' },
      { dia: 21, referencia: 'Salmos 100', titulo: 'Celebração e ação de graças' },
      { dia: 22, referencia: 'Salmos 103', titulo: 'Bendize, ó minha alma, ao Senhor' },
      { dia: 23, referencia: 'Salmos 118', titulo: 'A pedra rejeitada tornou-se angular' },
      { dia: 24, referencia: 'Salmos 121', titulo: 'Elevo os olhos para os montes' },
      { dia: 25, referencia: 'Salmos 125', titulo: 'Os que confiam no Senhor são como o Monte Sião' },
      { dia: 26, referencia: 'Salmos 127', titulo: 'Se o Senhor não edificar a casa' },
      { dia: 27, referencia: 'Salmos 133', titulo: 'A união fraternal' },
      { dia: 28, referencia: 'Salmos 139', titulo: 'A onisciência e onipresença de Deus' },
      { dia: 29, referencia: 'Salmos 145', titulo: 'A grandeza e a bondade do Senhor' },
      { dia: 30, referencia: 'Salmos 150', titulo: 'Tudo o que tem fôlego louve ao Senhor!' },
    ],
  },
  {
    id: 'plano_proverbios_31d_2026_v1',
    titulo: 'Provérbios: 31 Dias de Sabedoria',
    subtitulo: 'O livro da sabedoria prática. Leia 1 capítulo por dia durante um mês.',
    // Usamos um construtor de array dinâmico para os 31 dias de provérbios
    dias: Array.from({ length: 31 }, (_, i) => ({
      dia: i + 1,
      referencia: `Provérbios ${i + 1}`,
      titulo: `Provérbios Capítulo ${i + 1}`,
    })),
  },
  {
    id: 'plano_herois_fe_15d_2026_v1',
    titulo: 'Heróis da Fé (Antigo Testamento)',
    subtitulo: '15 dias conhecendo as histórias de homens e mulheres que marcaram a Bíblia.',
    dias: [
      { dia: 1, referencia: 'Gênesis 6', titulo: 'Noé e a Arca' },
      { dia: 2, referencia: 'Gênesis 12', titulo: 'O chamado de Abraão' },
      { dia: 3, referencia: 'Gênesis 22', titulo: 'A grande prova de Abraão' },
      { dia: 4, referencia: 'Gênesis 37', titulo: 'Os sonhos do jovem José' },
      { dia: 5, referencia: 'Gênesis 41', titulo: 'José, governador do Egito' },
      { dia: 6, referencia: 'Êxodo 3', titulo: 'O chamado de Moisés e a sarça ardente' },
      { dia: 7, referencia: 'Êxodo 14', titulo: 'A travessia do Mar Vermelho' },
      { dia: 8, referencia: 'Josué 6', titulo: 'Josué e a queda de Jericó' },
      { dia: 9, referencia: 'Juízes 6', titulo: 'O chamado de Gideão' },
      { dia: 10, referencia: 'Rute 1', titulo: 'A lealdade de Rute' },
      { dia: 11, referencia: '1 Samuel 17', titulo: 'A coragem de Davi diante de Golias' },
      { dia: 12, referencia: '1 Reis 18', titulo: 'Elias e os profetas de Baal no Carmelo' },
      { dia: 13, referencia: '2 Reis 5', titulo: 'A cura de Naamã e o profeta Eliseu' },
      { dia: 14, referencia: 'Ester 4', titulo: 'A ousadia da Rainha Ester' },
      { dia: 15, referencia: 'Daniel 6', titulo: 'Daniel e a cova dos leões' },
    ],
  },
  {
    id: 'plano_novo_testamento_6meses_2026_v2',
    titulo: 'Novo Testamento Completo (6 Meses)',
    subtitulo: 'Leitura integral de todos os 260 capítulos, de 1 de julho a 31 de dezembro.',
    dias: [
      ...Array.from({ length: 28 }, (_, i) => ({
        dia: i + 1,
        referencia: `Mateus ${i + 1}`,
        titulo: `Mateus Capítulo ${i + 1}`,
      })),

      ...Array.from({ length: 16 }, (_, i) => ({
        dia: 29 + i,
        referencia: `Marcos ${i + 1}`,
        titulo: `Marcos Capítulo ${i + 1}`,
      })),

      ...Array.from({ length: 24 }, (_, i) => ({
        dia: 45 + i,
        referencia: `Lucas ${i + 1}`,
        titulo: `Lucas Capítulo ${i + 1}`,
      })),

      ...Array.from({ length: 21 }, (_, i) => ({
        dia: 69 + i,
        referencia: `João ${i + 1}`,
        titulo: `João Capítulo ${i + 1}`,
      })),

      ...Array.from({ length: 28 }, (_, i) => ({
        dia: 90 + i,
        referencia: `Atos ${i + 1}`,
        titulo: `Atos Capítulo ${i + 1}`,
      })),

      { dia: 118, referencia: 'Romanos 1-2', titulo: 'Romanos 1 e 2' },
      { dia: 119, referencia: 'Romanos 3-4', titulo: 'Romanos 3 e 4' },
      { dia: 120, referencia: 'Romanos 5-6', titulo: 'Romanos 5 e 6' },
      { dia: 121, referencia: 'Romanos 7-8', titulo: 'Romanos 7 e 8' },
      { dia: 122, referencia: 'Romanos 9-10', titulo: 'Romanos 9 e 10' },
      { dia: 123, referencia: 'Romanos 11-12', titulo: 'Romanos 11 e 12' },
      { dia: 124, referencia: 'Romanos 13-14', titulo: 'Romanos 13 e 14' },
      { dia: 125, referencia: 'Romanos 15-16', titulo: 'Romanos 15 e 16' },
      { dia: 126, referencia: '1 Coríntios 1-2', titulo: '1 Coríntios 1 e 2' },
      { dia: 127, referencia: '1 Coríntios 3-4', titulo: '1 Coríntios 3 e 4' },
      { dia: 128, referencia: '1 Coríntios 5-6', titulo: '1 Coríntios 5 e 6' },
      { dia: 129, referencia: '1 Coríntios 7-8', titulo: '1 Coríntios 7 e 8' },
      { dia: 130, referencia: '1 Coríntios 9-10', titulo: '1 Coríntios 9 e 10' },
      { dia: 131, referencia: '1 Coríntios 11-12', titulo: '1 Coríntios 11 e 12' },
      { dia: 132, referencia: '1 Coríntios 13-14', titulo: '1 Coríntios 13 e 14' },
      { dia: 133, referencia: '1 Coríntios 15-16', titulo: '1 Coríntios 15 e 16' },
      { dia: 134, referencia: '2 Coríntios 1-3', titulo: '2 Coríntios 1 a 3' },
      { dia: 135, referencia: '2 Coríntios 4-5', titulo: '2 Coríntios 4 e 5' },
      { dia: 136, referencia: '2 Coríntios 6-7', titulo: '2 Coríntios 6 e 7' },
      { dia: 137, referencia: '2 Coríntios 8-9', titulo: '2 Coríntios 8 e 9' },
      { dia: 138, referencia: '2 Coríntios 10-11', titulo: '2 Coríntios 10 e 11' },
      { dia: 139, referencia: '2 Coríntios 12-13', titulo: '2 Coríntios 12 e 13' },
      { dia: 140, referencia: 'Gálatas 1-2', titulo: 'Gálatas 1 e 2' },
      { dia: 141, referencia: 'Gálatas 3-4', titulo: 'Gálatas 3 e 4' },
      { dia: 142, referencia: 'Gálatas 5-6', titulo: 'Gálatas 5 e 6' },
      { dia: 143, referencia: 'Efésios 1-2', titulo: 'Efésios 1 e 2' },
      { dia: 144, referencia: 'Efésios 3-4', titulo: 'Efésios 3 e 4' },
      { dia: 145, referencia: 'Efésios 5-6', titulo: 'Efésios 5 e 6' },
      { dia: 146, referencia: 'Filipenses 1-2', titulo: 'Filipenses 1 e 2' },
      { dia: 147, referencia: 'Filipenses 3-4', titulo: 'Filipenses 3 e 4' },
      { dia: 148, referencia: 'Colossenses 1-2', titulo: 'Colossenses 1 e 2' },
      { dia: 149, referencia: 'Colossenses 3-4', titulo: 'Colossenses 3 e 4' },
      { dia: 150, referencia: '1 Tessalonicenses 1-3', titulo: '1 Tessalonicenses 1 a 3' },
      { dia: 151, referencia: '1 Tessalonicenses 4-5', titulo: '1 Tessalonicenses 4 e 5' },
      { dia: 152, referencia: '2 Tessalonicenses 1-3', titulo: '2 Tessalonicenses 1 a 3' },
      { dia: 153, referencia: '1 Timóteo 1-3', titulo: '1 Timóteo 1 a 3' },
      { dia: 154, referencia: '1 Timóteo 4-6', titulo: '1 Timóteo 4 a 6' },
      { dia: 155, referencia: '2 Timóteo 1-2', titulo: '2 Timóteo 1 e 2' },
      { dia: 156, referencia: '2 Timóteo 3-4', titulo: '2 Timóteo 3 e 4' },
      { dia: 157, referencia: 'Tito 1-3', titulo: 'Tito 1 a 3' },
      { dia: 158, referencia: 'Filemom 1', titulo: 'Filemom 1' },
      { dia: 159, referencia: 'Hebreus 1-3', titulo: 'Hebreus 1 a 3' },
      { dia: 160, referencia: 'Hebreus 4-6', titulo: 'Hebreus 4 a 6' },
      { dia: 161, referencia: 'Hebreus 7-8', titulo: 'Hebreus 7 e 8' },
      { dia: 162, referencia: 'Hebreus 9-10', titulo: 'Hebreus 9 e 10' },
      { dia: 163, referencia: 'Hebreus 11-13', titulo: 'Hebreus 11 a 13' },
      { dia: 164, referencia: 'Tiago 1-3', titulo: 'Tiago 1 a 3' },
      { dia: 165, referencia: 'Tiago 4-5', titulo: 'Tiago 4 e 5' },
      { dia: 166, referencia: '1 Pedro 1-3', titulo: '1 Pedro 1 a 3' },
      { dia: 167, referencia: '1 Pedro 4-5', titulo: '1 Pedro 4 e 5' },
      { dia: 168, referencia: '2 Pedro 1-3', titulo: '2 Pedro 1 a 3' },
      { dia: 169, referencia: '1 João 1-3', titulo: '1 João 1 a 3' },
      { dia: 170, referencia: '1 João 4-5', titulo: '1 João 4 e 5' },
      { dia: 171, referencia: '2 João 1', titulo: '2 João 1' },
      { dia: 172, referencia: '3 João 1', titulo: '3 João 1' },
      { dia: 173, referencia: 'Judas 1', titulo: 'Judas 1' },

      ...Array.from({ length: 11 }, (_, i) => ({
        dia: 174 + i,
        referencia: `Apocalipse ${i * 2 + 1}-${i * 2 + 2}`,
        titulo: `Apocalipse ${i * 2 + 1} e ${i * 2 + 2}`,
      })),
    ],
  },
];
