export interface ItemPlanoLeitura {
  dia: number;
  referencia: string;
  titulo: string;
}

export interface PlanoLeitura {
  id: string;
  titulo: string;
  subtitulo: string;
  dias: ItemPlanoLeitura[];
}

export const PLANOS_LEITURA: PlanoLeitura[] = [
  {
    id: 'plano_fundamentos_fe_2026_v1',
    titulo: 'Fundamentos da Fé',
    subtitulo: 'Uma jornada rápida de 3 dias pelas origens da criação e a queda.',
    dias: [
      { dia: 1, referencia: 'Gênesis 1', titulo: 'A criação do mundo e do homem' },
      { dia: 2, referencia: 'Gênesis 2', titulo: 'O Jardim do Éden e o propósito' },
      { dia: 3, referencia: 'Gênesis 3', titulo: 'A desobediência e a promessa' },
    ],
  },
  {
    id: 'plano_coracao_pastor_2026_v1',
    titulo: 'O Coração do Pastor',
    subtitulo: '5 dias de refrigério espiritual através dos Salmos mais marcantes.',
    dias: [
      { dia: 1, referencia: 'Salmos 1', titulo: 'O caminho do bem e do mal' },
      { dia: 2, referencia: 'Salmos 8', titulo: 'A majestade de Deus e a dignidade humana' },
      { dia: 3, referencia: 'Salmos 23', titulo: 'O Senhor é o meu pastor' },
      { dia: 4, referencia: 'Salmos 27', titulo: 'O Senhor é a minha luz e salvação' },
      { dia: 5, referencia: 'Salmos 91', titulo: 'A habitação no esconderijo do Altíssimo' },
    ],
  },
  {
    id: 'plano_sabedoria_pratica_2026_v1',
    titulo: 'Sabedoria Diária',
    subtitulo: '7 dias de conselhos práticos para a vida em Provérbios.',
    dias: [
      { dia: 1, referencia: 'Provérbios 1', titulo: 'O princípio da sabedoria' },
      { dia: 2, referencia: 'Provérbios 3', titulo: 'Confiança e direção em Deus' },
      { dia: 3, referencia: 'Provérbios 4', titulo: 'As duas veredas da vida' },
      { dia: 4, referencia: 'Provérbios 15', titulo: 'Palavras que edificam' },
      { dia: 5, referencia: 'Provérbios 16', titulo: 'Os planos do coração' },
      { dia: 6, referencia: 'Provérbios 22', titulo: 'A boa reputação e a prudência' },
      { dia: 7, referencia: 'Provérbios 31', titulo: 'O valor da virtude' },
    ],
  },
  {
    id: 'plano_passos_mestre_2026_v1',
    titulo: 'Caminhando com o Mestre',
    subtitulo: '10 dias conhecendo os passos, milagres e ensinamentos de Jesus em Marcos.',
    dias: [
      { dia: 1, referencia: 'Marcos 1', titulo: 'O início do ministério e batismo' },
      { dia: 2, referencia: 'Marcos 2', titulo: 'O poder para perdoar pecados' },
      { dia: 3, referencia: 'Marcos 4', titulo: 'Parábolas do Reino e acalmando a tempestade' },
      { dia: 4, referencia: 'Marcos 5', titulo: 'Transformação de vidas e cura' },
      { dia: 5, referencia: 'Marcos 8', titulo: 'A identidade de Cristo e o verdadeiro discípulo' },
      { dia: 6, referencia: 'Marcos 9', titulo: 'A transfiguração e a fé' },
      { dia: 7, referencia: 'Marcos 10', titulo: 'O jovem rico e o verdadeiro servo' },
      { dia: 8, referencia: 'Marcos 12', titulo: 'O maior mandamento' },
      { dia: 9, referencia: 'Marcos 14', titulo: 'A última ceia e o Getsêmani' },
      { dia: 10, referencia: 'Marcos 16', titulo: 'A ressurreição e a Grande Comissão' },
    ],
  },
  {
    id: 'plano_vida_espirito_2026_v1',
    titulo: 'A Vida no Espírito',
    subtitulo: '14 dias profundos de transformação e justificação na carta aos Romanos.',
    dias: [
      { dia: 1, referencia: 'Romanos 1', titulo: 'O poder do evangelho' },
      { dia: 2, referencia: 'Romanos 2', titulo: 'O justo juízo de Deus' },
      { dia: 3, referencia: 'Romanos 3', titulo: 'A justificação pela fé' },
      { dia: 4, referencia: 'Romanos 4', titulo: 'O exemplo de Abraão' },
      { dia: 5, referencia: 'Romanos 5', titulo: 'Paz com Deus e a graça' },
      { dia: 6, referencia: 'Romanos 6', titulo: 'Mortos para o pecado, vivos para Deus' },
      { dia: 7, referencia: 'Romanos 7', titulo: 'O conflito interior' },
      { dia: 8, referencia: 'Romanos 8', titulo: 'A vida no Espírito' },
      { dia: 9, referencia: 'Romanos 10', titulo: 'A confissão de fé e a salvação' },
      { dia: 10, referencia: 'Romanos 12', titulo: 'O culto racional e a transformação' },
      { dia: 11, referencia: 'Romanos 13', titulo: 'O amor ao próximo e a conduta' },
      { dia: 12, referencia: 'Romanos 14', titulo: 'A acolhida na diversidade da fé' },
      { dia: 13, referencia: 'Romanos 15', titulo: 'A esperança para os gentios' },
      { dia: 14, referencia: 'Romanos 16', titulo: 'Saudações finais e doxologia' },
    ],
  },
  {
    id: 'plano_novo_testamento_6meses_2026_v1',
    titulo: 'Novo Testamento em 6 Meses',
    subtitulo:
      'Leitura diária de 1 de julho a 31 de dezembro para percorrer todo o Novo Testamento.',
    dias: [
      // MÊS 1: JULHO (Dias 1 a 31) - Mateus e Início de Marcos
      { dia: 1, referencia: 'Mateus 1', titulo: 'A genealogia e o nascimento de Jesus' },
      { dia: 2, referencia: 'Mateus 2', titulo: 'A visita dos magos e a fuga para o Egito' },
      { dia: 3, referencia: 'Mateus 3', titulo: 'O batismo de Jesus por João Batista' },
      { dia: 4, referencia: 'Mateus 4', titulo: 'A tentação no deserto e o início do ministério' },
      { dia: 5, referencia: 'Mateus 5', titulo: 'O Sermão da Montanha: As Bem-Aventuranças' },
      { dia: 6, referencia: 'Mateus 6', titulo: 'Ensinamentos sobre a oração e o Pai Nosso' },
      { dia: 7, referencia: 'Mateus 7', titulo: 'A regra de ouro e a casa sobre a rocha' },
      { dia: 8, referencia: 'Mateus 8', titulo: 'Milagres de cura e acalmando a tempestade' },
      { dia: 9, referencia: 'Mateus 9', titulo: 'O chamado de Mateus e o poder de perdoar' },
      { dia: 10, referencia: 'Mateus 10', titulo: 'O envio dos doze discípulos' },
      { dia: 11, referencia: 'Mateus 11', titulo: 'O jugo suave e o descanso para a alma' },
      { dia: 12, referencia: 'Mateus 12', titulo: 'O Senhor do Sábado e o poder de Deus' },
      { dia: 13, referencia: 'Mateus 13', titulo: 'Parábolas do Reino dos Céus' },
      {
        dia: 14,
        referencia: 'Mateus 14',
        titulo: 'A multiplicação dos pães e Jesus andando sobre o mar',
      },
      {
        dia: 15,
        referencia: 'Mateus 15',
        titulo: 'A tradição dos homens e a fé da mulher cananeia',
      },
      { dia: 16, referencia: 'Mateus 16', titulo: 'A confissão de Pedro e a pedra da igreja' },
      { dia: 17, referencia: 'Mateus 17', titulo: 'A transfiguração no monte' },
      { dia: 18, referencia: 'Mateus 18', titulo: 'O perdão e a ovelha perdida' },
      { dia: 19, referencia: 'Mateus 19', titulo: 'O casamento e o jovem rico' },
      { dia: 20, referencia: 'Mateus 20', titulo: 'A parábola dos trabalhadores da vinha' },
      { dia: 21, referencia: 'Mateus 21', titulo: 'A entrada triunfal em Jerusalém' },
      { dia: 22, referencia: 'Mateus 22', titulo: 'A parábola do banquete nupcial' },
      { dia: 23, referencia: 'Mateus 23', titulo: 'Ai dos escribas e fariseus' },
      { dia: 24, referencia: 'Mateus 24', titulo: 'Os sinais da vinda do Filho do Homem' },
      { dia: 25, referencia: 'Mateus 25', titulo: 'As parábolas das dez virgens e dos talentos' },
      { dia: 26, referencia: 'Mateus 26', titulo: 'A última ceia e a prisão no Getsêmani' },
      { dia: 27, referencia: 'Mateus 27', titulo: 'A crucificação e sepultamento de Jesus' },
      { dia: 28, referencia: 'Mateus 28', titulo: 'A ressurreição e a Grande Comissão' },
      { dia: 29, referencia: 'Marcos 1', titulo: 'O batismo e o início do ministério em Marcos' },
      { dia: 30, referencia: 'Marcos 2', titulo: 'O paralítico de Cafarnaum' },
      { dia: 31, referencia: 'Marcos 3', titulo: 'A escolha dos doze apóstolos' },

      // MÊS 2: AGOSTO (Dias 32 a 62) - Marcos, Lucas e Início de João
      { dia: 32, referencia: 'Marcos 4', titulo: 'A parábola do semeador' },
      { dia: 33, referencia: 'Marcos 5', titulo: 'A cura do endemoninhado gadareno' },
      { dia: 34, referencia: 'Marcos 6', titulo: 'A rejeição em Nazaré e a morte de João Batista' },
      { dia: 35, referencia: 'Marcos 7', titulo: 'O que contamina o homem' },
      { dia: 36, referencia: 'Marcos 8', titulo: 'A cura do cego em Betsaida' },
      { dia: 37, referencia: 'Marcos 9', titulo: 'A transfiguração e o poder da fé' },
      { dia: 38, referencia: 'Marcos 10', titulo: 'O caminho do sacrifício e o cego Bartimeu' },
      { dia: 39, referencia: 'Marcos 11', titulo: 'A figueira estéril e a purificação do templo' },
      { dia: 40, referencia: 'Marcos 12', titulo: 'A moeda de César e a oferta da viúva' },
      { dia: 41, referencia: 'Marcos 13', titulo: 'A vigilância para o fim dos tempos' },
      { dia: 42, referencia: 'Marcos 14', titulo: 'A unção em Betânia e a traição' },
      { dia: 43, referencia: 'Marcos 15', titulo: 'Jesus perante Pilatos e a crucificação' },
      { dia: 44, referencia: 'Marcos 16', titulo: 'Ressurreição: Ide por todo o mundo' },
      { dia: 45, referencia: 'Lucas 1', titulo: 'O nascimento de João Batista e Jesus anunciado' },
      { dia: 46, referencia: 'Lucas 2', titulo: 'O nascimento de Jesus em Belém' },
      { dia: 47, referencia: 'Lucas 3', titulo: 'A genealogia de Jesus segundo Lucas' },
      { dia: 48, referencia: 'Lucas 4', titulo: 'Jesus na sinagoga de Nazaré' },
      { dia: 49, referencia: 'Lucas 5', titulo: 'A pesca maravilhosa e chamados' },
      { dia: 50, referencia: 'Lucas 6', titulo: 'As bem-aventuranças e os ais' },
      { dia: 51, referencia: 'Lucas 7', titulo: 'A fé do centurião e o filho da viúva' },
      { dia: 52, referencia: 'Lucas 8', titulo: 'Mulheres que serviam a Jesus e a filha de Jairo' },
      { dia: 53, referencia: 'Lucas 9', titulo: 'A confissão de Pedro e a missão dos setenta' },
      { dia: 54, referencia: 'Lucas 10', titulo: 'A parábola do Bom Samaritano' },
      { dia: 55, referencia: 'Lucas 11', titulo: 'Ensino sobre a oração insistente' },
      { dia: 56, referencia: 'Lucas 12', titulo: 'A Parábola do Rico Insensato' },
      { dia: 57, referencia: 'Lucas 13', titulo: 'O arrependimento necessário' },
      { dia: 58, referencia: 'Lucas 14', titulo: 'A parábola do grande banquete' },
      { dia: 59, referencia: 'Lucas 15', titulo: 'A ovelha, a dracma e o filho perdidos' },
      { dia: 60, referencia: 'Lucas 16', titulo: 'O mordomo infiel e o rico e Lázaro' },
      { dia: 61, referencia: 'Lucas 17', titulo: 'A gratidão do leproso curado' },
      { dia: 62, referencia: 'Lucas 18', titulo: 'O juiz iníquo e o fariseu e o publicano' },

      // MÊS 3: SETEMBRO (Dias 63 a 92) - Fim de Lucas, João e Início de Atos
      { dia: 63, referencia: 'Lucas 19', titulo: 'Zaqueu transformado e a entrada em Jerusalém' },
      { dia: 64, referencia: 'Lucas 20', titulo: 'A autoridade de Jesus questionada' },
      { dia: 65, referencia: 'Lucas 21', titulo: 'A oferta da viúva pobre' },
      { dia: 66, referencia: 'Lucas 22', titulo: 'A instituição da Ceia do Senhor' },
      { dia: 67, referencia: 'Lucas 23', titulo: 'A cruz, o Calvário e o ladrão na cruz' },
      { dia: 68, referencia: 'Lucas 24', titulo: 'O caminho de Emaús e a ascensão' },
      { dia: 69, referencia: 'João 1', titulo: 'No princípio era o Verbo' },
      { dia: 70, referencia: 'João 2', titulo: 'As bodas de Caná: O primeiro milagre' },
      { dia: 71, referencia: 'João 3', titulo: 'Nicodemos e o novo nascimento (João 3:16)' },
      { dia: 72, referencia: 'João 4', titulo: 'A mulher samaritana à beira do poço' },
      { dia: 73, referencia: 'João 5', titulo: 'A cura no tanque de Betesda' },
      { dia: 74, referencia: 'João 6', titulo: 'Jesus é o Pão da Vida' },
      { dia: 75, referencia: 'João 7', titulo: 'A água viva na festa dos tabernáculos' },
      { dia: 76, referencia: 'João 8', titulo: 'A mulher pega em adultério e a Luz do Mundo' },
      { dia: 77, referencia: 'João 9', titulo: 'A cura do cego de nascença' },
      { dia: 78, referencia: 'João 10', titulo: 'O Bom Pastor dá a vida pelas ovelhas' },
      { dia: 79, referencia: 'João 11', titulo: 'A ressurreição de Lázaro' },
      { dia: 80, referencia: 'João 12', titulo: 'A unção em Betânia' },
      { dia: 81, referencia: 'João 13', titulo: 'O lava-pés e o novo mandamento' },
      { dia: 82, referencia: 'João 14', titulo: 'O Caminho, a Verdade e a Vida' },
      { dia: 83, referencia: 'João 15', titulo: 'A videira verdadeira e os ramos' },
      { dia: 84, referencia: 'João 16', titulo: 'A promessa do Espírito Santo Consolador' },
      { dia: 85, referencia: 'João 17', titulo: 'A oração sacerdotal de Jesus' },
      { dia: 86, referencia: 'João 18', titulo: 'A prisão e o julgamento perante Pilatos' },
      { dia: 87, referencia: 'João 19', titulo: 'Está consumado: A morte na cruz' },
      { dia: 88, referencia: 'João 20', titulo: 'Maria Madalena e Tomé no cenáculo' },
      { dia: 89, referencia: 'João 21', titulo: 'A pesca milagrosa e a restauração de Pedro' },
      { dia: 90, referencia: 'Atos 1', titulo: 'A ascensão e a promessa do Espírito Santo' },
      { dia: 91, referencia: 'Atos 2', titulo: 'O Dia de Pentecostes e o nascimento da igreja' },
      { dia: 92, referencia: 'Atos 3', titulo: 'A cura do coxo na Porta Formosa' },

      // MÊS 4: OUTUBRO (Dias 93 a 123) - Fim de Atos, Romanos e 1 Coríntios
      { dia: 93, referencia: 'Atos 4', titulo: 'Pedro e João perante o Sinédrio' },
      { dia: 94, referencia: 'Atos 5', titulo: 'Ananias e Safira; os apóstolos presos' },
      { dia: 95, referencia: 'Atos 6', titulo: 'A escolha dos sete diáconos' },
      { dia: 96, referencia: 'Atos 7', titulo: 'O testemunho e o apedrejamento de Estêvão' },
      { dia: 97, referencia: 'Atos 8', titulo: 'Filipe em Samaria e o etíope' },
      { dia: 98, referencia: 'Atos 9', titulo: 'A conversão de Saulo de Tarso' },
      { dia: 100, referencia: 'Atos 11', titulo: 'A igreja em Antioquia' },
      { dia: 99, referencia: 'Atos 10', titulo: 'Pedro e Cornélio: O evangelho para os gentios' },
      { dia: 101, referencia: 'Atos 12', titulo: 'A libertação milagrosa de Pedro' },
      { dia: 102, referencia: 'Atos 13', titulo: 'A primeira viagem missionária de Paulo' },
      { dia: 103, referencia: 'Atos 14', titulo: 'Em Icônio, Listra e Derbe' },
      { dia: 104, referencia: 'Atos 15', titulo: 'O Concílio de Jerusalém' },
      { dia: 105, referencia: 'Atos 16', titulo: 'A prisão de Paulo e Silas em Filipos' },
      { dia: 106, referencia: 'Atos 17', titulo: 'Paulo em Tessalônica e Atenas' },
      { dia: 107, referencia: 'Atos 18', titulo: 'O ministério em Corinto' },
      { dia: 108, referencia: 'Atos 19', titulo: 'O avivamento em Éfeso' },
      { dia: 109, referencia: 'Atos 20', titulo: 'O discurso de despedida em Mileto' },
      { dia: 110, referencia: 'Atos 21', titulo: 'A viagem de volta e a prisão em Jerusalém' },
      { dia: 111, referencia: 'Atos 22', titulo: 'A defesa de Paulo ao povo' },
      { dia: 112, referencia: 'Atos 23', titulo: 'O complô contra Paulo' },
      { dia: 113, referencia: 'Atos 24', titulo: 'Paulo perante Félix' },
      { dia: 114, referencia: 'Atos 25', titulo: 'Paulo apela para César' },
      { dia: 115, referencia: 'Atos 26', titulo: 'O testemunho perante o rei Agripa' },
      { dia: 116, referencia: 'Atos 27', titulo: 'A tempestade e o naufrágio' },
      { dia: 117, referencia: 'Atos 28', titulo: 'A chegada a Roma e prisão domiciliar' },
      { dia: 118, referencia: 'Romanos 1', titulo: 'O poder do evangelho para a salvação' },
      { dia: 119, referencia: 'Romanos 2', titulo: 'A imparcialidade do juízo divino' },
      { dia: 120, referencia: 'Romanos 3', titulo: 'Todos pecaram e carecem da glória' },
      { dia: 121, referencia: 'Romanos 4', titulo: 'A justificação pela fé de Abraão' },
      { dia: 122, referencia: 'Romanos 5', titulo: 'Paz com Deus por meio de Cristo' },
      { dia: 123, referencia: 'Romanos 6', titulo: 'Mortos para o pecado, livres na graça' },

      // MÊS 5: NOVEMBRO (Dias 124 a 153) - Fim de Romanos até Hebreus
      { dia: 124, referencia: 'Romanos 7', titulo: 'O conflito interior contra o pecado' },
      { dia: 125, referencia: 'Romanos 8', titulo: 'A vida no Espírito e a segurança eterna' },
      { dia: 126, referencia: 'Romanos 9', titulo: 'A soberania de Deus na eleição' },
      { dia: 127, referencia: 'Romanos 10', titulo: 'A confissão de fé e a pregação' },
      { dia: 128, referencia: 'Romanos 11', titulo: 'O remanescente eleito de Israel' },
      { dia: 129, referencia: 'Romanos 12', titulo: 'O culto racional e a transformação' },
      { dia: 130, referencia: 'Romanos 13', titulo: 'Deveres cívicos e o amor ao próximo' },
      { dia: 131, referencia: 'Romanos 14', titulo: 'Acolhimento aos fracos na fé' },
      { dia: 132, referencia: 'Romanos 15', titulo: 'O ministério aos gentios' },
      { dia: 133, referencia: 'Romanos 16', titulo: 'Saudações finais e doxologia' },
      { dia: 134, referencia: '1 Coríntios 1', titulo: 'A loucura da cruz' },
      { dia: 135, referencia: '1 Coríntios 2', titulo: 'A sabedoria revelada pelo Espírito' },
      { dia: 136, referencia: '1 Coríntios 3', titulo: 'Cooperadores de Deus' },
      { dia: 137, referencia: '1 Coríntios 4', titulo: 'A fidelidade na mordomia' },
      { dia: 138, referencia: '1 Coríntios 5', titulo: 'Disciplina na comunidade' },
      { dia: 139, referencia: '1 Coríntios 6', titulo: 'O corpo como templo do Espírito' },
      { dia: 140, referencia: '1 Coríntios 7', titulo: 'Orientações sobre o casamento' },
      { dia: 141, referencia: '1 Coríntios 8', titulo: 'A questão dos alimentos sacrificados' },
      { dia: 142, referencia: '1 Coríntios 9', titulo: 'Os direitos e deveres do obreiro' },
      { dia: 143, referencia: '1 Coríntios 10', titulo: 'Advertências contra a idolatria' },
      { dia: 144, referencia: '1 Coríntios 11', titulo: 'A instituição da Santa Ceia' },
      { dia: 145, referencia: '1 Coríntios 12', titulo: 'Os dons espirituais no Corpo' },
      { dia: 146, referencia: '1 Coríntios 13', titulo: 'O capítulo do amor' },
      { dia: 147, referencia: '1 Coríntios 14', titulo: 'Profecia e línguas na igreja' },
      { dia: 148, referencia: '1 Coríntios 15', titulo: 'A certeza da ressurreição' },
      { dia: 149, referencia: '1 Coríntios 16', titulo: 'Coleta para os santos e saudações' },
      { dia: 150, referencia: '2 Coríntios 1', titulo: 'O Deus de toda a consolação' },
      { dia: 151, referencia: '2 Coríntios 2', titulo: 'O triunfo em Cristo' },
      {
        dia: 152,
        referencia: '2 Coríntios 3',
        titulo: 'O ministério do Espírito e da Nova Aliança',
      },
      { dia: 153, referencia: '2 Coríntios 4', titulo: 'Tesouros em vasos de barro' },

      // MÊS 6: DEZEMBRO (Dias 154 a 184) - Fim das Cartas Gerais e Apocalipse
      { dia: 154, referencia: '2 Coríntios 5', titulo: 'A nova criação em Cristo' },
      { dia: 155, referencia: '2 Coríntios 6', titulo: 'Cooperadores com Deus' },
      { dia: 156, referencia: '2 Coríntios 7', titulo: 'A tristeza segundo Deus' },
      { dia: 157, referencia: '2 Coríntios 8', titulo: 'A generosidade na contribuição' },
      { dia: 158, referencia: '2 Coríntios 9', titulo: 'Deus ama quem dá com alegria' },
      { dia: 159, referencia: '2 Coríntios 10', titulo: 'As armas da nossa milícia' },
      { dia: 160, referencia: '2 Coríntios 11', titulo: 'Os sofrimentos de Paulo pelo evangelho' },
      { dia: 161, referencia: '2 Coríntios 12', titulo: 'A graça me basta na fraqueza' },
      { dia: 162, referencia: '2 Coríntios 13', titulo: 'Advertências e saudações finais' },
      { dia: 163, referencia: 'Gálatas 1', titulo: 'Não há outro evangelho' },
      { dia: 164, referencia: 'Gálatas 2', titulo: 'Justificados pela fé em Cristo' },
      { dia: 165, referencia: 'Gálatas 3', titulo: 'A lei como aia e a promessa a Abraão' },
      { dia: 166, referencia: 'Gálatas 4', titulo: 'Filhos e herdeiros por adoção' },
      { dia: 167, referencia: 'Gálatas 5', titulo: 'O fruto do Espírito' },
      { dia: 168, referencia: 'Gálatas 6', titulo: 'A lei de Cristo e a semeadura' },
      { dia: 169, referencia: 'Efésios 1', titulo: 'As bênçãos espirituais em Cristo' },
      { dia: 170, referencia: 'Efésios 2', titulo: 'Salvos pela graça mediante a fé' },
      { dia: 171, referencia: 'Efésios 3', titulo: 'O mistério revelado aos gentios' },
      { dia: 172, referencia: 'Efésios 4', titulo: 'A unidade e o crescimento do Corpo' },
      { dia: 173, referencia: 'Efésios 5', titulo: 'Andai como filhos da luz' },
      { dia: 174, referencia: 'Efésios 6', titulo: 'A armadura de Deus' },
      { dia: 175, referencia: 'Filipenses 1', titulo: 'Para mim o viver é Cristo' },
      { dia: 176, referencia: 'Filipenses 2', titulo: 'A humilhação e exaltação de Cristo' },
      { dia: 177, referencia: 'Filipenses 3', titulo: 'Alvo para o prêmio da soberana vocação' },
      { dia: 178, referencia: 'Filipenses 4', titulo: 'Alegrai-vos sempre no Senhor' },
      { dia: 179, referencia: 'Colossenses 1', titulo: 'A supremacia de Cristo' },
      { dia: 180, referencia: 'Colossenses 2', titulo: 'Completos em Cristo' },
      { dia: 181, referencia: 'Colossenses 3', titulo: 'Pensai nas coisas lá do alto' },
      { dia: 182, referencia: 'Colossenses 4', titulo: 'Perseverança na oração' },
      { dia: 183, referencia: 'Apocalipse 1', titulo: 'A revelação de Jesus Cristo' },
      { dia: 184, referencia: 'Apocalipse 22', titulo: 'Eis que venho sem demora' },
    ],
  },
];
