name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Dependências
        run: npm ci --legacy-peer-deps

      - name: Gerar Arquivo Environment com Variáveis
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          VAPID_PUBLICKEY: ${{ secrets.VAPID_PUBLIC_KEY }}
        run: |

      - name: Build do Projeto (Angular)
        run: npm run build -- --configuration production --base-href /app-ibfc/

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/app-ibfc/browser
